import { useMemo, useState } from 'react'
import { BUILD_PHOTO_BY_ID } from '../../data/buildPhotos'
import { ENCLOSURE_CAMERA_PRESETS, ENCLOSURE_SLOT_BY_ID, ENCLOSURE_SLOTS } from '../../data/enclosure'
import { sourceAssetUrl } from '../../data/sourceReferences'
import { validateConnectionGraph } from '../../utils/connections'
import { enclosureStlLoadFailureMessage, stagingPlacementFor, validateEnclosure } from '../../utils/enclosure'
import type { EnclosurePartId, EnclosurePlacement, LabAction, LabState } from '../../types'
import EnclosureViewport from './EnclosureViewport'

interface Props { state: LabState; dispatch: (action: LabAction) => void }
const BUILD_THREE = BUILD_PHOTO_BY_ID.get('build-three-enclosure')!

function partLabel(partId: EnclosurePartId) {
  return {
    'triad-spectral-sensor': 'AS7265x TRIAD spectrometer', 'pcf8523-clock': 'PCF8523 real-time clock', 'oled-display': '0.91-inch OLED display', 'thing-plus-rp2040': 'Thing Plus RP2040', 'i2c-button': 'Pushbutton module', 'power-switch': 'Battery disconnect switch', 'battery-400': 'Rechargeable 400 mAh battery', 'micro-sd-card': 'microSD card',
  }[partId]
}

function placementFor(state: LabState, partId: EnclosurePartId, slotId: string | null, rotationZ?: number): EnclosurePlacement {
  const current = state.enclosurePlacements.find((placement) => placement.partId === partId) ?? stagingPlacementFor(partId)
  const slot = slotId ? ENCLOSURE_SLOT_BY_ID.get(slotId) : undefined
  return slot ? {
    partId, slotId, positionMm: slot.positionMm, rotation: [slot.rotation[0], slot.rotation[1], rotationZ ?? slot.rotation[2]], seated: true,
  } : current
}

export default function EnclosureWorkspace({ state, dispatch }: Props) {
  const [loadError, setLoadError] = useState<string | null>(null)
  const [loaded, setLoaded] = useState(false)
  const graph = useMemo(() => validateConnectionGraph(state.layoutPlacements, state.step6Connections, state.coinCellInstalled), [state.layoutPlacements, state.step6Connections, state.coinCellInstalled])
  const validation = useMemo(() => validateEnclosure(state.layoutPlacements, state.step6Connections, state.coinCellInstalled, state.enclosurePlacements, state.microSdInstalled), [state.layoutPlacements, state.step6Connections, state.coinCellInstalled, state.enclosurePlacements, state.microSdInstalled])
  const selectedPart = state.selectedEnclosureComponentId ?? 'triad-spectral-sensor'
  const selectedPlacement = state.enclosurePlacements.find((placement) => placement.partId === selectedPart) ?? stagingPlacementFor(selectedPart)
  const activeSlot = state.selectedEnclosureSlotId ? ENCLOSURE_SLOT_BY_ID.get(state.selectedEnclosureSlotId) : undefined
  const locked = graph.status !== 'valid'
  const enterFullscreen = () => {
    const viewport = document.querySelector('[data-stella-enclosure-viewport]')
    if (viewport instanceof HTMLElement && document.fullscreenEnabled) void viewport.requestFullscreen()
  }

  const dropPart = (partId: EnclosurePartId, positionMm: readonly [number, number, number]) => {
    const target = ENCLOSURE_SLOTS.find((slot) => slot.acceptedPartId === partId)
    const closeEnough = target && Math.hypot(positionMm[0] - target.positionMm[0], positionMm[1] - target.positionMm[1]) <= target.positionToleranceMm * 1.75
    dispatch({ type: 'PLACE_ENCLOSURE_COMPONENT', placement: closeEnough ? placementFor(state, partId, target.id) : { ...stagingPlacementFor(partId), positionMm, rotation: selectedPlacement.rotation } })
  }

  if (locked) return <section className="sq2-panel rounded-sm p-6" aria-labelledby="enclosure-locked-title"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-amber-300">Step 7 locked</p><h2 id="enclosure-locked-title" className="mt-2 text-xl font-semibold text-white">Validate the connected assembly first</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-400">Step 7 preserves the exact Step 6 graph while the connected electronics move into the housing. Return to Step 6 to repair cables or install the CR1220; Step 7 cannot reconnect anything.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" className="sq2-focus rounded-sm bg-cyan-300 px-4 py-2 text-xs font-semibold text-[#03101c]" onClick={() => dispatch({ type: 'SELECT_BUILD_STEP', stepId: 'cable-connections' })}>Return to Step 6</button><button type="button" className="sq2-focus rounded-sm border border-white/15 px-4 py-2 text-xs" onClick={() => dispatch({ type: 'CHECK_CONNECTIONS' })}>Check Step 6</button></div><ul className="mt-4 list-disc space-y-1 pl-5 text-xs text-slate-400">{graph.messages.map((message) => <li key={message}>{message}</li>)}</ul></section>

  return <section className="space-y-4" aria-labelledby="enclosure-workspace-title">
    <div className="sq2-panel rounded-sm p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[9px] font-semibold uppercase tracking-[0.2em] text-cyan-300">Step 7 · connected enclosure placement</p><h2 id="enclosure-workspace-title" className="mt-1 text-lg font-semibold text-white">Seat the Build 2 assembly in the supplied top housing</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-400">The original top-housing STL and Build 3 photograph are shown together. Retainers are only translucent reserved regions in the reference; they are not installable until Step 8. Cable curves are intentionally loose until Step 9.</p></div><div className="flex flex-wrap gap-2">{(['workspace', 'build-three', 'side-by-side', 'overlay'] as const).map((mode) => <button key={mode} type="button" onClick={() => dispatch({ type: 'SET_ENCLOSURE_COMPARISON_MODE', mode })} aria-pressed={state.enclosureComparisonMode === mode} className={`sq2-focus rounded-sm border px-3 py-2 text-[10px] font-semibold capitalize ${state.enclosureComparisonMode === mode ? 'border-cyan-300 bg-cyan-300/10 text-cyan-200' : 'border-white/15 text-slate-400'}`}>{mode.replace('-', ' ')}</button>)}</div></div></div>

    {state.enclosureComparisonMode !== 'build-three' && <div className={state.enclosureComparisonMode === 'side-by-side' ? 'grid gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]' : ''}><div data-stella-enclosure-viewport><EnclosureViewport placements={state.enclosurePlacements} connections={state.step6Connections} selectedPartId={state.selectedEnclosureComponentId} selectedSlotId={state.selectedEnclosureSlotId} cameraPreset={state.enclosureCameraPreset} showTargets={state.enclosureTargetsVisible || state.guidance === 'beginner'} showCables={state.enclosureCablesVisible} transparentHousing={state.enclosureTransparentHousing || state.enclosureComparisonMode === 'overlay'} wireframeHousing={state.enclosureWireframeHousing} isolateSelected={state.enclosureIsolateSelected} guidance={state.guidance} onSelectPart={(partId) => dispatch({ type: 'SELECT_ENCLOSURE_COMPONENT', partId })} onSelectSlot={(slotId) => dispatch({ type: 'SELECT_ENCLOSURE_SLOT', slotId })} onDropPart={dropPart} onLoadError={(error) => setLoadError(error.message)} onLoaded={() => setLoaded(true)} /></div>{state.enclosureComparisonMode === 'side-by-side' && <BuildThreeReference />}</div>}
    {state.enclosureComparisonMode === 'build-three' && <BuildThreeReference wide />}
    {loadError && <div role="alert" className="rounded-sm border border-rose-300/30 bg-rose-300/10 p-3 text-xs text-rose-100">{enclosureStlLoadFailureMessage()} <button type="button" className="ml-2 underline" onClick={() => { setLoadError(null); setLoaded(false) }}>Retry</button></div>}
    {!loaded && !loadError && <p className="text-[10px] text-slate-500" role="status">Loading the cleaned supplied top-housing STL…</p>}

    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_19rem]"><div className="sq2-panel rounded-sm p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-[0.2em] text-cyan-300">Placement controls</p><h3 className="mt-1 text-sm font-semibold text-white">Drag in 3D or use the accessible placement builder</h3></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => dispatch({ type: 'UNDO_ENCLOSURE' })} disabled={!state.enclosureUndoHistory.length} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px] disabled:opacity-30">Undo</button><button type="button" onClick={() => dispatch({ type: 'REDO_ENCLOSURE' })} disabled={!state.enclosureRedoHistory.length} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px] disabled:opacity-30">Redo</button><button type="button" onClick={() => dispatch({ type: 'RESET_ENCLOSURE' })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">Reset Step 7</button></div></div>
      <div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-[10px] font-semibold text-slate-400">Connected component<select value={selectedPart} onChange={(event) => dispatch({ type: 'SELECT_ENCLOSURE_COMPONENT', partId: event.target.value as EnclosurePartId })} className="mt-1 block w-full rounded-sm border border-white/15 bg-[#030916] px-2 py-2 text-xs text-white">{state.enclosurePlacements.map((placement) => <option key={placement.partId} value={placement.partId}>{partLabel(placement.partId)}{placement.seated ? ' · seated' : ' · staged'}</option>)}</select></label><label className="text-[10px] font-semibold text-slate-400">Housing slot<select value={state.selectedEnclosureSlotId ?? ''} onChange={(event) => dispatch({ type: 'SELECT_ENCLOSURE_SLOT', slotId: event.target.value || null })} className="mt-1 block w-full rounded-sm border border-white/15 bg-[#030916] px-2 py-2 text-xs text-white"><option value="">Choose slot</option>{ENCLOSURE_SLOTS.map((slot) => <option key={slot.id} value={slot.id}>{slot.label}{slot.acceptedPartId === selectedPart ? '' : ' · incompatible'}</option>)}</select></label><div className="flex items-end gap-2"><button type="button" onClick={() => activeSlot && dispatch({ type: 'PLACE_ENCLOSURE_COMPONENT', placement: placementFor(state, selectedPart, activeSlot.id) })} disabled={!activeSlot} className="sq2-focus min-h-10 flex-1 rounded-sm bg-cyan-300 px-3 text-xs font-semibold text-[#03101c] disabled:opacity-30">Place into slot</button><button type="button" onClick={() => dispatch({ type: 'REMOVE_ENCLOSURE_COMPONENT', partId: selectedPart })} className="sq2-focus min-h-10 rounded-sm border border-white/15 px-3 text-xs">Remove</button></div></div>
      <div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => dispatch({ type: 'ROTATE_ENCLOSURE_COMPONENT', partId: selectedPart, delta: -90 })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">Rotate −90°</button><button type="button" onClick={() => dispatch({ type: 'ROTATE_ENCLOSURE_COMPONENT', partId: selectedPart, delta: 90 })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">Rotate +90°</button><button type="button" onClick={() => dispatch({ type: 'SELECT_ENCLOSURE_SLOT', slotId: ENCLOSURE_SLOTS.find((slot) => slot.acceptedPartId === selectedPart)?.id ?? null })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">Fit selected component</button><button type="button" onClick={() => dispatch({ type: 'TOGGLE_ENCLOSURE_ISOLATION' })} aria-pressed={state.enclosureIsolateSelected} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">{state.enclosureIsolateSelected ? 'Show all cables' : 'Isolate selected cable'}</button><button type="button" onClick={() => dispatch({ type: 'SELECT_BUILD_STEP', stepId: 'cable-connections' })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">Return to Step 6 to change connections</button></div>
      <p className="mt-3 text-[10px] leading-5 text-slate-500">Selected: {partLabel(selectedPart)}. {activeSlot ? activeSlot.orientationNote : 'Choose its source-backed housing slot to review its orientation and insertion axis.'}</p></div>
      <aside className="sq2-panel rounded-sm p-4"><p className="text-[9px] font-semibold uppercase tracking-[0.2em] text-cyan-300">Placement checklist</p><ul className="mt-3 space-y-2 text-xs">{state.enclosurePlacements.map((placement) => <li key={placement.partId} className="flex items-center justify-between gap-2"><span className="text-slate-300">{partLabel(placement.partId)}</span><span className={placement.seated ? 'text-emerald-300' : 'text-amber-200'}>{placement.seated ? '✓ seated' : '○ staged'}</span></li>)}</ul><button type="button" onClick={() => dispatch({ type: 'CHECK_ENCLOSURE' })} className="sq2-focus mt-4 w-full rounded-sm bg-cyan-300 px-3 py-2 text-xs font-semibold text-[#03101c]">Check Step 7</button><div className="mt-3 rounded-sm border border-white/10 bg-black/20 p-3 text-[10px] leading-5 text-slate-400" role="status">{state.enclosureValidation === 'idle' ? 'Place every connected part, then check the step.' : validation.messages.join(' ')}</div></aside></div>

    <div className="sq2-panel rounded-sm p-4"><div className="flex flex-wrap gap-2">{ENCLOSURE_CAMERA_PRESETS.map((preset) => <button key={preset} type="button" onClick={() => dispatch({ type: 'SET_ENCLOSURE_CAMERA', preset })} aria-pressed={state.enclosureCameraPreset === preset} className={`sq2-focus rounded-sm border px-3 py-2 text-[10px] capitalize ${state.enclosureCameraPreset === preset ? 'border-cyan-300 text-cyan-200' : 'border-white/15 text-slate-400'}`}>{preset === 'build-three' ? 'angled Build 3' : preset}</button>)}<button type="button" onClick={enterFullscreen} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">Fullscreen</button><button type="button" onClick={() => dispatch({ type: 'TOGGLE_ENCLOSURE_TARGETS' })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">{state.enclosureTargetsVisible ? 'Hide slots' : 'Show slots'}</button><button type="button" onClick={() => dispatch({ type: 'TOGGLE_ENCLOSURE_CABLES' })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">{state.enclosureCablesVisible ? 'Hide cable curves' : 'Show cable curves'}</button><button type="button" onClick={() => dispatch({ type: 'TOGGLE_ENCLOSURE_TRANSPARENCY' })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">{state.enclosureTransparentHousing ? 'Opaque housing' : 'Transparent housing'}</button><button type="button" onClick={() => dispatch({ type: 'TOGGLE_ENCLOSURE_WIREFRAME' })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">{state.enclosureWireframeHousing ? 'Solid housing' : 'Wireframe housing'}</button><button type="button" onClick={() => dispatch({ type: 'TOGGLE_ENCLOSURE_HINT' })} className="sq2-focus rounded-sm border border-white/15 px-3 py-2 text-[10px]">{state.enclosureHintVisible ? 'Hide hint' : 'Show hint'}</button></div>{state.enclosureHintVisible && <p className="mt-3 border-l-2 border-cyan-300 bg-cyan-300/[0.06] px-3 py-2 text-xs leading-5 text-slate-300">Suggested order from Build 3: TRIAD, RTC, OLED, RP2040, microSD card, button, switch, then battery. The CR1220 stays installed in the RTC. Retainer clips shown beside the photo are reference-only until Step 8.</p>}<p className="mt-3 text-[10px] text-slate-500">Scene summary: {state.enclosurePlacements.filter((placement) => placement.seated).length} of {state.enclosurePlacements.length} source-required items seated; all six Step 6 connections remain centrally preserved.</p></div>
  </section>
}

function BuildThreeReference({ wide = false }: { wide?: boolean }) { return <figure className={`sq2-panel overflow-hidden rounded-sm ${wide ? 'max-w-5xl' : ''}`}><div className="border-b border-white/10 px-4 py-3"><p className="text-[9px] font-semibold uppercase tracking-[0.2em] text-cyan-300">Official Build 3 reference</p><p className="mt-1 text-xs text-slate-400">Target component placement. Retainers shown at left are installed in Step 8; wire routing is Step 9.</p></div><div className="bg-black/30 p-3"><img src={sourceAssetUrl(BUILD_THREE.assetPath)} alt={BUILD_THREE.alt} className="max-h-[42rem] w-full object-contain" /></div><figcaption className="px-4 py-3 text-[10px] leading-5 text-slate-500">{BUILD_THREE.caption} · zoom with browser controls or use the 3D camera presets alongside this source photograph.</figcaption></figure> }
