// Shared data layer for the STELLA Data Visualizer.
//
// One normalized shape (`StellaDataset`) serves both the bundled NASA sample
// datasets (src/data/stellaSamples.json, generated by scripts/fetch_stella_data.py)
// and CSV files users drop in from their own STELLA device. The upload parser
// mirrors the Python normalizer: same canonical env keys, same spectral triplets.

import { ndvi } from '../data/games.js'

// ---------- types -------------------------------------------------------------

/** [wavelength nm, irradiance, uncertainty|null] */
export type SpecTriplet = [number, number | null, number | null]

export interface StellaRecord {
  /** timestamp, ms since epoch (UTC) */
  t: number
  batch: number
  env: Record<string, number>
  spec: SpecTriplet[]
}

export interface StellaDataset {
  id: string
  instrument: string
  title: string
  description: string
  credit: string
  sourceUrl: string | null
  /** irradiance unit of `spec` values (differs by device); null when no spectra */
  specUnit: string | null
  originalRows: number
  envFields: string[]
  records: StellaRecord[]
  /** true when this dataset came from a user-uploaded file (never leaves the browser) */
  uploaded?: boolean
}

export interface FieldMeta {
  label: string
  unit: string
  /** short teaching note for the data dictionary */
  note: string
}

export interface Stats {
  n: number
  min: number
  max: number
  mean: number
  std: number
}

// ---------- canonical env-field registry --------------------------------------

export const ENV_FIELDS: Record<string, FieldMeta> = {
  surface_temp_C: {
    label: 'Surface temperature',
    unit: '°C',
    note: 'Non-contact thermal reading of whatever the instrument is pointed at.',
  },
  air_temp_C: {
    label: 'Air temperature',
    unit: '°C',
    note: 'Ambient air temperature at the instrument.',
  },
  co2_temp_C: {
    label: 'Air temp (CO₂ sensor)',
    unit: '°C',
    note: 'Second temperature reading, from the CO₂ sensor package.',
  },
  rh_pct: {
    label: 'Relative humidity',
    unit: '%',
    note: 'How much water vapor the air holds vs. its maximum.',
  },
  co2_rh_pct: {
    label: 'Humidity (CO₂ sensor)',
    unit: '%',
    note: 'Second humidity reading, from the CO₂ sensor package.',
  },
  pressure_hPa: {
    label: 'Barometric pressure',
    unit: 'hPa',
    note: 'Atmospheric pressure; changes with weather and altitude.',
  },
  altitude_m: {
    label: 'Altitude (uncalibrated)',
    unit: 'm',
    note: 'Estimated from pressure: relative changes are meaningful, absolute values are not.',
  },
  lidar_m: {
    label: 'LiDAR range',
    unit: 'm',
    note: 'Laser-measured distance from the instrument to the target.',
  },
  battery_v: {
    label: 'Battery voltage',
    unit: 'V',
    note: 'Instrument health: useful for spotting when readings degrade.',
  },
  aqi: { label: 'Air-quality index (PM)', unit: '', note: 'Particulate-based air-quality index.' },
  co2_ppm: {
    label: 'CO₂ concentration',
    unit: 'ppm',
    note: 'Carbon-dioxide concentration; outdoor background is ~420 ppm.',
  },
  pm1_ugm3: { label: 'PM1 concentration', unit: 'µg/m³', note: 'Fine particles under 1 µm.' },
  pm25_ugm3: {
    label: 'PM2.5 concentration',
    unit: 'µg/m³',
    note: 'Fine particles under 2.5 µm: the key health metric.',
  },
  pm10_ugm3: { label: 'PM10 concentration', unit: 'µg/m³', note: 'Coarse particles under 10 µm.' },
  cnt03_p100ml: { label: 'Particles ≥0.3 µm', unit: '/100 mL', note: 'Raw particle count.' },
  cnt05_p100ml: { label: 'Particles ≥0.5 µm', unit: '/100 mL', note: 'Raw particle count.' },
  cnt25_p100ml: { label: 'Particles ≥2.5 µm', unit: '/100 mL', note: 'Raw particle count.' },
  lux: { label: 'Illuminance', unit: 'lux', note: 'Total visible-light intensity.' },
  uva: { label: 'UVA', unit: 'counts', note: 'Ultraviolet-A sensor reading (~320 nm).' },
}

export function fieldMeta(key: string): FieldMeta {
  return ENV_FIELDS[key] ?? { label: key, unit: '', note: 'Field from the device CSV.' }
}

// ---------- small parsing helpers ----------------------------------------------

function toNum(v: string | undefined): number | null {
  if (v == null) return null
  const f = parseFloat(String(v).trim())
  return Number.isFinite(f) ? f : null
}

/** ISO8601 basic (20230728T174449Z) → ms, or null. */
export function parseStellaTimestamp(s: string | undefined): number | null {
  if (!s) return null
  const m = /^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/.exec(s.trim())
  if (!m) return null
  const [, y, mo, d, h, mi, se] = m
  return Date.UTC(+y, +mo - 1, +d, +h, +mi, +se)
}

/** Minimal CSV splitter (STELLA files are simple; handles quoted cells). */
export function parseCsv(text: string): string[][] {
  const clean = text.replace(/�/g, ' ').replace(/ /g, ' ')
  const out: string[][] = []
  for (const line of clean.split(/\r?\n/)) {
    if (!line.trim()) continue
    const row: string[] = []
    let cur = ''
    let inQ = false
    for (let i = 0; i < line.length; i++) {
      const c = line[i]
      if (inQ) {
        if (c === '"' && line[i + 1] === '"') { cur += '"'; i++ }
        else if (c === '"') inQ = false
        else cur += c
      } else if (c === '"') inQ = true
      else if (c === ',') { row.push(cur); cur = '' }
      else cur += c
    }
    row.push(cur)
    out.push(row.map((c) => c.replace(/\s+/g, ' ').trim()))
  }
  return out
}

// ---------- instrument detection + upload normalization ------------------------

export type InstrumentKind = 'stella-q2' | 'stella-1-1' | 'stella-aq' | 'helio-stella'

export function detectInstrument(header: string[]): InstrumentKind | null {
  const h = header.map((x) => x.toLowerCase())
  if (h.some((x) => /^irradiance_\d+nm_.*_irradiance_uw_per_cm_squared$/.test(x))) return 'stella-q2'
  if (h.some((x) => /^(?:[a-z]+)?\d{3}_irradiance_uw_per_cm_squared$/.test(x))) return 'stella-1-1'
  if (h[0] === 'stella-aq' || h.includes('co2_ppm')) return 'stella-aq'
  if (h.includes('lux_center_nm') || h.some((x) => x.includes('irradiance_w/(m^2*nm)'))) return 'helio-stella'
  return null
}

const findCol = (header: string[], name: string) =>
  header.findIndex((h) => h.toLowerCase() === name.toLowerCase())

interface BandCol { nm: number; irr: number; unc: number | null }

function extractRecords(
  header: string[],
  rows: string[][],
  opts: {
    tsCol: string
    batchCol: string
    envMap: Record<string, string>
    bands: BandCol[]
    luxSaturation?: boolean
  },
): StellaRecord[] {
  const tsI = findCol(header, opts.tsCol)
  const batchI = findCol(header, opts.batchCol)
  const envIdx: [string, number][] = Object.entries(opts.envMap)
    .map(([k, name]) => [k, findCol(header, name)] as [string, number])
    .filter(([, i]) => i >= 0)
  const records: StellaRecord[] = []
  for (const r of rows) {
    const t = tsI >= 0 ? parseStellaTimestamp(r[tsI]) : null
    if (t == null) continue
    const env: Record<string, number> = {}
    for (const [k, i] of envIdx) {
      const v = toNum(r[i])
      if (v == null) continue
      if (opts.luxSaturation && k === 'lux' && v >= 99999) continue
      env[k] = v
    }
    const spec: SpecTriplet[] = opts.bands.map((b) => [
      b.nm,
      toNum(r[b.irr]),
      b.unc != null ? toNum(r[b.unc]) : null,
    ])
    records.push({ t, batch: Math.trunc(toNum(r[batchI]) ?? 0), env, spec })
  }
  return records
}

/**
 * Parse a raw STELLA CSV (user upload) into a StellaDataset.
 * Throws with a friendly message when the file isn't a recognizable STELLA CSV.
 */
export function parseStellaCsv(text: string, fileName: string): StellaDataset {
  const rows = parseCsv(text)
  if (rows.length < 2) throw new Error('That file looks empty: it needs a header row plus data rows.')
  const header = rows[0]
  const body = rows.slice(1)
  const kind = detectInstrument(header)
  if (!kind) {
    throw new Error(
      'That CSV doesn\'t look like a STELLA file. Expected headers like "irradiance_450nm_…", "V450_irradiance_…", "CO2_ppm", or "lux_center_nm".',
    )
  }

  let records: StellaRecord[] = []
  let specUnit: string | null = 'µW/cm²'
  let instrument = ''

  if (kind === 'stella-q2') {
    instrument = 'STELLA-Q2'
    const bands: BandCol[] = []
    header.forEach((h, i) => {
      const m = /^irradiance_(\d+)nm_.*_irradiance_uW_per_cm_squared$/i.exec(h)
      if (m) {
        const unc = header[i + 1]?.toLowerCase().includes('uncertainty') ? i + 1 : null
        bands.push({ nm: +m[1], irr: i, unc })
      }
    })
    bands.sort((a, b) => a.nm - b.nm)
    records = extractRecords(header, body, {
      tsCol: 'timestamp_iso8601',
      batchCol: 'batch',
      envMap: { battery_v: 'battery_voltage' },
      bands,
    })
  } else if (kind === 'stella-1-1') {
    instrument = 'STELLA-1.1'
    const bands: BandCol[] = []
    header.forEach((h, i) => {
      const m = /^(?:[A-Za-z]+)?(\d{3})_irradiance_uW_per_cm_squared$/i.exec(h)
      if (m) {
        const unc = header[i + 1]?.toLowerCase().includes('error') ? i + 1 : null
        bands.push({ nm: +m[1], irr: i, unc })
      }
    })
    bands.sort((a, b) => a.nm - b.nm)
    records = extractRecords(header, body, {
      tsCol: 'timestamp',
      batchCol: 'batch_number',
      envMap: {
        surface_temp_C: 'surface_temperature_C',
        air_temp_C: 'air_temperature_C',
        rh_pct: 'relative_humidity_percent',
        pressure_hPa: 'barometric_pressure_hPa',
        altitude_m: 'altitude_uncalibrated_m',
        lidar_m: 'LiDAR_range_m',
        battery_v: 'battery_voltage',
      },
      bands,
    })
  } else if (kind === 'stella-aq') {
    instrument = 'STELLA-AQ'
    specUnit = null
    records = extractRecords(header, body, {
      tsCol: 'timestamp',
      batchCol: 'batch',
      envMap: {
        aqi: 'AQIp',
        co2_ppm: 'CO2_ppm',
        co2_temp_C: 'CO2_sensor_air_temperature_C',
        co2_rh_pct: 'CO2_sensor_relative_humidity_%',
        air_temp_C: 'WX_sensor_air_temperature_C',
        rh_pct: 'WX_sensor_relative_humidity_%',
        pressure_hPa: 'WX_sensor_barometric_pressure_hPa',
        pm1_ugm3: '1um_concentration_ug_m^3',
        pm25_ugm3: '2_5um_concentration_ug_m^3',
        pm10_ugm3: '10um_concentration_ug_m^3',
        cnt03_p100ml: '0_3um_count_p_100mL',
        cnt05_p100ml: '0_5um_count_p_100mL',
        cnt25_p100ml: '2_5um_count_p_100mL',
        battery_v: 'battery_voltage',
      },
      bands: [],
    })
  } else {
    instrument = 'Helio-STELLA'
    specUnit = 'W/(m²·nm)'
    const colors = ['violet', 'indigo', 'blue', 'cyan', 'green', 'yellow', 'orange', 'red']
    const bands: BandCol[] = []
    for (const c of colors) {
      const nmI = findCol(header, `${c}_center_nm`)
      const irrI = header.findIndex((h) =>
        new RegExp(`^${c}_+irradiance_W/\\(m\\^2\\*nm\\)$`, 'i').test(h),
      )
      if (nmI >= 0 && irrI >= 0) {
        // center nm varies per row minimally; read from first data row
        const nm = toNum(body[0]?.[nmI])
        if (nm != null) bands.push({ nm: Math.round(nm), irr: irrI, unc: null })
      }
    }
    bands.sort((a, b) => a.nm - b.nm)
    records = extractRecords(header, body, {
      tsCol: 'timestamp_iso8601',
      batchCol: 'batch',
      envMap: {
        lux: 'lux',
        uva: 'uva',
        air_temp_C: 'air_temperature_C',
        rh_pct: 'relative_humidity_percent',
        pressure_hPa: 'barometric_pressure_hPa',
        battery_v: 'battery_voltage',
      },
      bands,
      luxSaturation: true,
    })
  }

  if (records.length === 0) {
    throw new Error('Recognized the instrument, but found no rows with a valid ISO8601 timestamp.')
  }
  records.sort((a, b) => a.t - b.t)
  const envFields = [...new Set(records.flatMap((r) => Object.keys(r.env)))].sort()

  return {
    id: `upload-${Date.now()}`,
    instrument,
    title: fileName,
    description: `Your ${instrument} file, parsed locally in the browser (${records.length} records). It never leaves this device.`,
    credit: 'Data: your STELLA instrument.',
    sourceUrl: null,
    specUnit,
    originalRows: records.length,
    envFields,
    records,
    uploaded: true,
  }
}

// ---------- analysis helpers ----------------------------------------------------

export function computeStats(values: number[]): Stats | null {
  const v = values.filter((x) => Number.isFinite(x))
  if (v.length === 0) return null
  let min = Infinity
  let max = -Infinity
  let sum = 0
  for (const x of v) {
    if (x < min) min = x
    if (x > max) max = x
    sum += x
  }
  const mean = sum / v.length
  let sq = 0
  for (const x of v) sq += (x - mean) * (x - mean)
  return { n: v.length, min, max, mean, std: Math.sqrt(sq / v.length) }
}

export function envSeries(ds: StellaDataset, key: string): { t: number; v: number }[] {
  const out: { t: number; v: number }[] = []
  for (const r of ds.records) {
    const v = r.env[key]
    if (Number.isFinite(v)) out.push({ t: r.t, v })
  }
  return out
}

function bandNearest(spec: SpecTriplet[], target: number, lo: number, hi: number): number | null {
  let best: SpecTriplet | null = null
  for (const b of spec) {
    if (b[0] < lo || b[0] > hi || b[1] == null) continue
    if (!best || Math.abs(b[0] - target) < Math.abs(best[0] - target)) best = b
  }
  return best ? best[1] : null
}

/**
 * Irradiance-based greenness estimate for one record: (NIR − red)/(NIR + red)
 * using the bands nearest 650 nm (red) and 860 nm (NIR). Proper NDVI requires
 * reflectance (white-reference calibration); this is a teaching estimate.
 * Returns null when the instrument lacks a NIR band (e.g. Helio-STELLA).
 */
export function greennessForRecord(r: StellaRecord): number | null {
  const red = bandNearest(r.spec, 650, 620, 690)
  const nir = bandNearest(r.spec, 860, 780, 950)
  if (red == null || nir == null || red + nir <= 0) return null
  return ndvi(red, nir)
}

export function hasNirBand(ds: StellaDataset): boolean {
  return ds.records.some((r) => r.spec.some((b) => b[0] >= 780))
}

/** Field-report rows: stats for every env field + each spectral band. */
export function datasetReport(ds: StellaDataset): { key: string; label: string; unit: string; stats: Stats }[] {
  const rows: { key: string; label: string; unit: string; stats: Stats }[] = []
  for (const key of ds.envFields) {
    const stats = computeStats(ds.records.map((r) => r.env[key]).filter((v): v is number => v != null))
    if (stats) rows.push({ key, label: fieldMeta(key).label, unit: fieldMeta(key).unit, stats })
  }
  const nms = [...new Set(ds.records.flatMap((r) => r.spec.map((b) => b[0])))].sort((a, b) => a - b)
  for (const nm of nms) {
    const vals: number[] = []
    for (const r of ds.records) {
      const b = r.spec.find((x) => x[0] === nm)
      if (b && b[1] != null) vals.push(b[1])
    }
    const stats = computeStats(vals)
    if (stats) rows.push({ key: `band_${nm}`, label: `Band ${nm} nm`, unit: ds.specUnit ?? '', stats })
  }
  return rows
}

/** Derived-data CSV (client-side download): per-record env + greenness. */
export function derivedCsv(ds: StellaDataset): string {
  const keys = ds.envFields
  const header = ['timestamp_utc', 'batch', ...keys, 'greenness_estimate']
  const lines = [header.join(',')]
  for (const r of ds.records) {
    const g = greennessForRecord(r)
    lines.push(
      [
        new Date(r.t).toISOString(),
        r.batch,
        ...keys.map((k) => (r.env[k] != null ? r.env[k] : '')),
        g != null ? g.toFixed(4) : '',
      ].join(','),
    )
  }
  return lines.join('\n')
}
