// Short, well-established facts about Earth shown while Mission Control loads.
// General science-education content — not tied to any specific mission or
// live data source.

export const EARTH_FACTS: string[] = [
  'Earth is the only known planet with liquid water covering most of its surface.',
  "Earth's atmosphere is roughly 78% nitrogen and 21% oxygen, with trace gases making up the rest.",
  'A day on Earth is slowly getting longer — tidal friction from the Moon adds about 1.8 milliseconds per century.',
  "Earth's magnetic field is generated by the churning of molten iron and nickel in its outer core.",
  'Most Earth-observing satellites fly in low Earth orbit, only a few hundred kilometers up — closer to the surface than many cities are wide.',
  'Sun-synchronous orbits let a satellite pass over the same spot at roughly the same local time every day, which is useful for comparing images over months or years.',
  'About 71% of Earth’s surface is covered by ocean, but the ocean floor is less thoroughly mapped than the surface of the Moon.',
  'Earth is not a perfect sphere — it bulges slightly at the equator due to its rotation.',
  'The ozone layer, mostly in the stratosphere, absorbs most of the Sun’s harmful ultraviolet radiation.',
  'Weather satellites in geostationary orbit stay above the same point on Earth by matching its 24-hour rotation from about 35,786 km up.',
  'Earth’s tectonic plates move a few centimeters a year — roughly the speed fingernails grow.',
  'Radar instruments like SAR can image Earth’s surface through clouds and darkness, since they supply their own signal instead of relying on sunlight.',
  'The Arctic and Antarctic lose more heat to space in the far-infrared than almost anywhere else on Earth — a key part of the planet’s energy balance.',
  'Earth’s gravity field is not perfectly uniform — it varies slightly with the mass of mountains, oceans, and even groundwater underground.',
  'Green plants and phytoplankton absorb carbon dioxide and release oxygen, linking Earth’s land, ocean, and atmosphere in a single carbon cycle.',
  'Ground-based and satellite instruments both measure the same sunlight — reflected or emitted electromagnetic energy — just from very different vantage points.',
]

export function randomEarthFact(excludeIndex = -1): { fact: string; index: number } {
  if (EARTH_FACTS.length <= 1) return { fact: EARTH_FACTS[0], index: 0 }
  let index = Math.floor(Math.random() * EARTH_FACTS.length)
  if (index === excludeIndex) index = (index + 1) % EARTH_FACTS.length
  return { fact: EARTH_FACTS[index], index }
}
